# Generated by Django 5.0.2 on 2024-02-28 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fragments', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DecimalValues',
            new_name='players',
        ),
    ]
