# Generated by Django 5.0.2 on 2024-02-29 10:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragments', '0004_payoutdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payoutdata',
            name='current_date_time',
        ),
        migrations.AddField(
            model_name='payoutdata',
            name='current_datetime_ist',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
