# Generated by Django 5.0.2 on 2024-02-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragments', '0005_remove_payoutdata_current_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
