# Generated by Django 5.0.2 on 2024-03-03 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragments', '0006_alter_players_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sess',
            name='player_ids',
            field=models.CharField(default='1,2,3', max_length=255),
        ),
    ]
