# Generated by Django 5.0.2 on 2024-03-03 04:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragments', '0007_sess_player_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payoutdata',
            name='fragsPaid',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
